from . import hr_config_settings
from . import hr_termination
from . import hr_resignation
from . import hr_retirement
from . import hr_suspended
from . import hr_employee_inherit
from . import hr_contracts
from . import turnover_reason
from . import hr_payslip